# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_version=1.11

# Minecraft Version Information
minecraft_version=1.20.1
minecraft_range=[1.20.1,1.20.2)

# check these on https://fabricmc.net/versions.html
loader_version=0.17.2
fabric_version=0.92.6+1.20.1
parchment_version=2021.12.19

# Build dependencies
jei_version=15.3.+

rei_version=12.0.622
jei_version=15.2.0.23
emi_version=1.1.22
# https://www.curseforge.com/minecraft/mc-mods/architectury-api
architectury_version=9.1.12
# https://github.com/JamiesWhiteShirt/reach-entity-attributes/releases
reach_entity_attributes_version = 2.4.0
# https://github.com/Ladysnake/Satin/releases
satin_version = 1.11.0
modmenu_version=7.2.1
cca_version=5.2.3

port_lib_version = 2.3.15
port_lib_modules = accessors,attributes,base,core,common,config,data,entity,extensions,models,model_loader,model_generators,networking,tags,transfer,fluids,lazy_registration,loot,utility
star_version = 1.5.2
